FROM node:18

# 作者
LABEL org.opencontainers.image.authors="zhangjichengcc <https://github.com/zhangjichengcc>"

# 设置工作目录
WORKDIR /app

# 复制项目
COPY . .

# 安装依赖
# RUN npm install
RUN npm install docsify-cli@4.4.4 -g && docsify --version

# 暴露端口
EXPOSE 3001

# 启动命令
CMD ["npm", "start"]