# main.yml
name: deploy docs to aliyun
# 触发方式
on:
  push:
    branches:
      - main

# 任务
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REMOTE_HOST: 118.190.52.53
      REMOTE_USER: root
      TARGET_PATH: /opt/service-container/webServer/my-docs
      TARGET_DIR: docs

    # 步骤
    steps:
      # 切换分支
      - name: Checkout
        # 先将仓库的代码checkout到环境中，github提供了checkout的方法，只需要我们加上这条即可
        uses: actions/checkout@master
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      # 链接服务器-备份原代码
      - name: Connect Server, Backup and Upload Code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.REMOTE_HOST }}
          username: ${{ env.REMOTE_USER }}
          key: ${{ secrets.AL_ACCESS_TOKEN }}
          script: |
            cd ${{ env.TARGET_PATH }}
            # 备份项目
            if [ -d "./${{ env.TARGET_DIR }}" ]; then
              tar czvf ${{ env.TARGET_DIR }}_$(date "+%Y%m%d(%H%M%S)").tar.gz ${{ env.TARGET_DIR }} --remove-files
              echo "原项目已备份"
            else
              echo "无需备份"
            fi

            # 拉取最新的 Git 代码
            git pull origin master

            # 上传新的代码文件
            rsync -avz --delete ./ ${{ env.TARGET_PATH }}/${{ env.TARGET_DIR }}/
