name: deploy docs to aliyun

# 触发方式
on:
  push:
    branches:
      - main

# 任务
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REMOTE_HOST: 118.190.52.53
      REMOTE_USER: root
      TARGET_PATH: /opt/service-container/webServer/my-docs
      TARGET_DIR: docs

    # 步骤
    steps:
      # 1. 切换分支并获取代码
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: main # 确保拉取的是 main 分支

      # 2. 安装 Node.js
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      # 3. 链接服务器、备份原代码并上传新的代码
      - name: Connect Server, Backup and Upload Code
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ env.REMOTE_HOST }}
          username: ${{ env.REMOTE_USER }}
          key: ${{ secrets.AL_ACCESS_TOKEN }}
          script: |
            cd ${{ env.TARGET_PATH }}

            # 备份项目
            if [ -d "./${{ env.TARGET_DIR }}" ]; then
              tar czf ${{ env.TARGET_DIR }}_$(date "+%Y%m%d(%H%M%S)").tar.gz ${{ env.TARGET_DIR }} --remove-files
              echo "原项目已备份"
            else
              echo "无需备份"
            fi

            # 拉取最新的 Git 代码
            git pull origin main

            # 上传新的代码文件
            rsync -avz --delete ./ ${{ env.TARGET_PATH }}/${{ env.TARGET_DIR }}/

            echo "代码上传完成"
