name: deploy docs to aliyun

# 触发方式
on:
  push:
    branches:
      - main

# 任务
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REMOTE_HOST: 118.190.52.53
      REMOTE_USER: root
      TARGET_PATH: /opt/service-container/webServer/my-docs
      TARGET_DIR: docs

    steps:
      # 切换分支并获取代码
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: main # 确保拉取的是 main 分支

      # 安装 Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'

      # 3. 设置 GITHUB_WORKSPACE 环境变量
      - name: Set GITHUB_WORKSPACE as ENV variable
        run: echo "WORKSPACE_PATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      # 链接服务器、备份原代码
      - name: Connect Server, Backup and Upload Code
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ env.REMOTE_HOST }}
          username: ${{ env.REMOTE_USER }}
          key: ${{ secrets.AL_ACCESS_TOKEN }}
          script: |
            cd ${{ env.TARGET_PATH }}

            # 备份项目
            if [ -d "./${{ env.TARGET_DIR }}" ]; then
              tar czf ${{ env.TARGET_DIR }}_$(date "+%Y%m%d_%H%M%S").tar.gz ${{ env.TARGET_DIR }} --remove-files
              echo "原项目已备份"
            else
              echo "无需备份"
            fi

            echo "上传项目: ${WORKSPACE_PATH}"

            # rsync -avz --delete \
            #   -e "ssh -o StrictHostKeyChecking=no" \
            #   ${WORKSPACE_PATH}/ ${{ env.TARGET_PATH }}/${{ env.TARGET_DIR }}/
